import moment from "moment-timezone";
export const LSTHEADER_TABLE = [
  {
    Field: "EmployeeCode",
    Caption: "Mã nhân viên",
    Width: 150,
    Fixed: true,
    Template: "",
    Alignment: "",
    Format: "",
    DataType: "",
    IsCheck: true,
  },
  {
    Field: "FullName",
    Caption: "Người nộp đơn",
    Width: 220,
    Fixed: true,
    Template: "fullname-template",
    Alignment: "",
    Format: "",
    DataType: "",
    IsCheck: true,
  },
  {
    Field: "PositionName",
    Caption: "Vị trí công việc",
    Width: 220,
    Fixed: false,
    Template: "",
    Alignment: "",
    Format: "",
    DataType: "",
    IsCheck: true,
  },
  {
    Field: "DepartmentName",
    Caption: "Đơn vị công tác",
    Width: 220,
    Fixed: false,
    Template: "",
    Alignment: "",
    Format: "",
    DataType: "",
    IsCheck: true,
  },
  {
    Field: "SubmitDate",
    Caption: "Ngày nộp đơn",
    Width: 150,
    Fixed: false,
    Template: "",
    Alignment: "center",
    Format: "dd/MM/yyyy HH:mm",
    DataType: "date",
    IsCheck: true,
  },
  {
    Field: "DateFrom",
    Caption: "Từ ngày",
    Width: 150,
    Fixed: false,
    Template: "",
    Alignment: "",
    Format: "dd/MM/yyyy HH:mm",
    DataType: "date",
    IsCheck: true,
  },
  {
    Field: "DateTo",
    Caption: "Đến ngày",
    Width: 150,
    Fixed: false,
    Template: "",
    Alignment: "",
    Format: "dd/MM/yyyy HH:mm",
    DataType: "date",
    IsCheck: true,
  },
  {
    Field: "NumRest",
    Caption: "Số ngày nghỉ",
    Width: 120,
    Fixed: false,
    Template: "",
    Alignment: "",
    Format: "",
    DataType: "",
    IsCheck: true,
  },
  {
    Field: "HourRest",
    Caption: "Số giờ nghỉ",
    Width: 120,
    Fixed: false,
    Template: "",
    Alignment: "",
    Format: "",
    DataType: "",
    IsCheck: true,
  },
  {
    Field: "TypeRestName",
    Caption: "Loại nghỉ",
    Width: 110,
    Fixed: false,
    Template: "",
    Alignment: "",
    Format: "",
    DataType: "",
    IsCheck: true,
  },
  {
    Field: "SalaryPercent",
    Caption: "Tỷ lệ hưởng lương",
    Width: 120,
    Fixed: false,
    Template: "",
    Alignment: "",
    Format: "",
    DataType: "",
    IsCheck: true,
  },
  {
    Field: "ReasonRest",
    Caption: "Lý do nghỉ",
    Width: 220,
    Fixed: false,
    Template: "",
    Alignment: "",
    Format: "",
    DataType: "",
    IsCheck: true,
  },
  {
    Field: "ApplyPersonName",
    Caption: "Người duyệt",
    Width: 170,
    Fixed: false,
    Template: "",
    Alignment: "",
    Format: "",
    DataType: "",
    IsCheck: false,
  },
  {
    Field: "SwapPersonName",
    Caption: "Người thay thế",
    Width: 220,
    Fixed: false,
    Template: "",
    Alignment: "",
    Format: "",
    DataType: "",
    InTextColumn: (data) => {
      if (!data.value) return "_";
    },
    IsCheck: false,
  },
  {
    Field: "RelatePersonName",
    Caption: "Người liên quan",
    Width: 220,
    Fixed: false,
    Template: "",
    Alignment: "",
    Format: "",
    DataType: "",
    InTextColumn: (data) => {
      if (!data.value) return "_";
    },
    IsCheck: false,
  },
  {
    Field: "NoteRest",
    Caption: "Ghi chú",
    Width: 110,
    Fixed: false,
    Template: "",
    Alignment: "center",
    Format: "",
    DataType: "",
    InTextColumn: (data) => {
      if (!data.value) return "_";
    },
    IsCheck: true,
  },
  {
    Field: "StatusName",
    Caption: "Trạng thái",
    Width: 126,
    Fixed: false,
    Template: "status",
    Alignment: "",
    Format: "",
    DataType: "",
    IsCheck: true,
  },
];

export const FILTER_OPTIONS = [
  {
    Caption: "Mã nhân viên",
    Field: "EmployeeCode",
    IsCheck: false,
    Operator: "%",
    Type: "",
    Value: "",
  },
  {
    Caption: "Người nộp đơn",
    Field: "FullName",
    IsCheck: false,
    Operator: "%",
    Type: "",
    Value: "",
  },
  {
    Caption: "Vị trí công việc",
    Field: "PositionName",
    IsCheck: false,
    Operator: "%",
    Type: "",
    Value: "",
  },
  {
    Caption: "Đơn vị công tác",
    Field: "DepartmentName",
    IsCheck: false,
    Operator: "%",
    Type: "",
    Value: "",
  },
  {
    Caption: "Ngày nộp đơn",
    Field: "SubmitDate",
    IsCheck: false,
    Operator: "=",
    Type: "date",
    Value: "",
  },
  {
    Caption: "Từ ngày",
    Field: "DateFrom",
    IsCheck: false,
    Operator: "=",
    Type: "date",
    Value: "",
  },
  {
    Caption: "Đến ngày",
    Field: "DateTo",
    IsCheck: false,
    Operator: "=",
    Type: "date",
    Value: "",
  },
  {
    Caption: "Số ngày nghỉ",
    Field: "NumRest",
    IsCheck: false,
    Operator: "%",
    Type: "",
    Value: "",
  },
  {
    Caption: "Số giờ nghỉ",
    Field: "HourRest",
    IsCheck: false,
    Operator: "%",
    Type: "",
    Value: "",
  },
  {
    Caption: "Loại nghỉ",
    Field: "TypeRestName",
    IsCheck: false,
    Operator: "%",
    Type: "",
    Value: "",
  },
  {
    Caption: "Tỷ lệ hưởng lương",
    Field: "SalaryPercent",
    IsCheck: false,
    Operator: "%",
    Type: "",
    Value: "",
  },
  {
    Caption: "Lý do nghỉ",
    Field: "ReasonRest",
    IsCheck: false,
    Operator: "%",
    Type: "",
    Value: "",
  },
  {
    Caption: "Người duyệt",
    Field: "ApplyPersonName",
    IsCheck: false,
    Operator: "%",
    Type: "",
    Value: "",
  },
  {
    Caption: "Người thay thế",
    Field: "SwapPersonName",
    IsCheck: false,
    Operator: "%",
    Type: "",
    Value: "",
  },
  {
    Caption: "Người liên quan",
    Field: "RelatePersonName",
    IsCheck: false,
    Operator: "%",
    Type: "",
    Value: "",
  },
  {
    Caption: "Ghi chú",
    Field: "NoteRest",
    IsCheck: false,
    Operator: "%",
    Type: "",
    Value: "",
  },
  {
    Caption: "Trạng thái",
    Field: "StatusName",
    IsCheck: false,
    Operator: "%",
    Type: "",
    Value: "",
  },
];

export const FILTERS_OPERATOR = [
  { OperatorName: "Bằng", Operator: "=" },
  { OperatorName: "Khác", Operator: "!=" },
  { OperatorName: "Chứa", Operator: "%" },
  { OperatorName: "Không chứa", Operator: "!%" },
];
